// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXiM4uU6GPMOQWxorASrCBk8fWia6iAkY',
    appId: '1:52121275407:web:09bd71adaab27491fce77a',
    messagingSenderId: '52121275407',
    projectId: 'myflutterapp-eba56',
    authDomain: 'myflutterapp-eba56.firebaseapp.com',
    storageBucket: 'myflutterapp-eba56.appspot.com',
    measurementId: 'G-SNP2VTLYDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qDTS01JzQxA32nyFjUpHkeP8sILls_k',
    appId: '1:52121275407:android:b967410b467dc7e6fce77a',
    messagingSenderId: '52121275407',
    projectId: 'myflutterapp-eba56',
    storageBucket: 'myflutterapp-eba56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-lnIQlhrsHjMKqNPBrizBnLgmDF4fTNs',
    appId: '1:52121275407:ios:4093a555d0b8c73cfce77a',
    messagingSenderId: '52121275407',
    projectId: 'myflutterapp-eba56',
    storageBucket: 'myflutterapp-eba56.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-lnIQlhrsHjMKqNPBrizBnLgmDF4fTNs',
    appId: '1:52121275407:ios:62596954fc787dedfce77a',
    messagingSenderId: '52121275407',
    projectId: 'myflutterapp-eba56',
    storageBucket: 'myflutterapp-eba56.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
